In [1]:
import pandas as pd
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

In [2]:
climate_data = pd.read_table('data/scraped_climate_info.csv', sep=',', header=0, engine='python')

In [3]:
gdp_data = pd.read_table('data/gdpdata.csv', sep=',', header=0, engine='python')

In [4]:
olympics_data = pd.read_table('data/athlete_events.csv', sep=',', header=0, engine='python')

In [5]:
climate_data.head()

        Country Average Temperature
0  Burkina Faso               28.25
1          Mali               28.25
2      Kiribati               28.20
3      Djibouti               28.00
4        Tuvalu               28.00

In [6]:
gdp_data.head()

        Name  2019 Population  GDP (IMF)  GDP (UN '16)  GDP Per Capita
0   Zimbabwe        17297.495     21.067     16.123764     1217.922017
1     Zambia        18137.369     27.217     21.063064     1500.603533
2      Yemen        29579.986     17.452     25.374086      589.993518
3    Vietnam        97429.061    264.939    205.276171     2719.301585
4  Venezuela        32779.868     92.417    291.376437     2819.321908

In [7]:
olympics_data.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [8]:
gdp_data.rename(columns={'Name':'Country'}, inplace=True)

In [9]:
common_countries = pd.merge(climate_data, gdp_data, how='inner', on=['Country'])
climate_gdp = common_countries[['Country','Average Temperature', 'GDP Per Capita']]

In [10]:
climate_data.shape

(191, 2)

In [11]:
gdp_data.shape

(211, 5)

In [12]:
common_countries.head()

,Country,Average Temperature,2019 Population,GDP (IMF),GDP (UN '16),GDP Per Capita
0,Burkina Faso,28.25,20321.560,15.867,11.695117,780.796356
1,Mali,28.25,19689.140,19.247,14.001697,977.543966
2,Kiribati,28.20,120.428,0.220,0.173655,1826.817684
3,Djibouti,28.00,985.690,2.380,1.891520,2414.552243
4,Tuvalu,28.00,11.393,0.045,0.036697,3949.793733

In [13]:
climate_gdp.head()

        Country Average Temperature  GDP Per Capita
0  Burkina Faso               28.25      780.796356
1          Mali               28.25      977.543966
2      Kiribati               28.20     1826.817684
3      Djibouti               28.00     2414.552243
4        Tuvalu               28.00     3949.793733

In [14]:
climate_gdp['Average Temperature'] = climate_gdp['Average Temperature'].str.replace('−', '-').astype(float)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [15]:
olympics_data = olympics_data.replace({'Medal' : { 'Gold' : 1, 'Silver' : 2, 'Bronze' : 3}})
olympics_data['Medal'] = olympics_data['Medal'].fillna(0)

In [17]:
olympics_data.shape

(271116, 11)

In [18]:
olympics_data.rename(columns={'Team':'Country'}, inplace=True)

In [19]:
olympics_data = olympics_data.dropna()

In [20]:
olympics_data = olympics_data[olympics_data['Year'].between(1980, 2018, inclusive=True)].sort_values(by=['Year'])

In [21]:
olympics = pd.merge(olympics_data, climate_gdp, how='inner', on=['Country'])
olympics.shape

(130324, 13)

In [22]:
olympics_csv = olympics.to_csv (r'data/olympics.csv', index = None, header=True)

In [23]:
data = pd.read_table('data/olympics.csv', sep=',', header=0, engine='python')

In [24]:
data

,Name,Sex,Age,Height,Weight,Country,Year,Season,Sport,Event,Medal,Average Temperature,GDP Per Capita
0,Leszek Hensler,M,24.0,172.0,70.0,Poland,1980,Summer,Hockey,Hockey Men's Hockey,0.0,7.85,17091.859905
1,Stanisaw Wierzbicki,M,21.0,189.0,87.0,Poland,1980,Summer,Rowing,Rowing Men's Quadruple Sculls,0.0,7.85,17091.859905
2,Jacek Maria Wierzchowiecki,M,36.0,170.0,68.0,Poland,1980,Summer,Equestrianism,"Equestrianism Mixed Three-Day Event, Individual",0.0,7.85,17091.859905
3,Barbara Bronisawa Baran-Wojnar,F,20.0,168.0,55.0,Poland,1980,Summer,Athletics,Athletics Women's Long Jump,0.0,7.85,17091.859905
4,Wadysaw Stecyk,M,29.0,156.0,52.0,Poland,1980,Summer,Wrestling,"Wrestling Men's Flyweight, Freestyle",2.0,7.85,17091.859905
5,Jacek Maria Wierzchowiecki,M,36.0,170.0,68.0,Poland,1980,Summer,Equestrianism,"Equestrianism Mixed Three-Day Event, Team",0.0,7.85,17091.859905
6,Alfred Jzef Kauziski,M,27.0,190.0,81.0,Poland,1980,Summer,Handball,Handball Men's Handball,0.0,7.85,17091.859905
7,Stanisaw Hubert Kawulok,M,26.0,171.0,68.0,Poland,1980,Winter,Nordic Combined,Nordic Combined Men's Individual,0.0,7.85,17091.859905
8,Leszek Jan Grski,M,18.0,184.0,85.0,Poland,1980,Summer,Swimming,Swimming Men's 400 metres Individual Medley,0.0,7.85,17091.859905
9,Zygmunt Gosiewski,M,20.0,182.0,71.0,Poland,1980,Summer,Boxing,Boxing Men's Light-Middleweight,0.0,7.85,17091.859905
10,Ryszard Burak,M,26.0,185.0,92.0,Poland,1980,Summer,Rowing,Rowing Men's Quadruple Sculls,0.0,7.85,17091.859905
11,Adam Starostka,M,23.0,180.0,79.0,Poland,1980,Summer,Athletics,Athletics Men's 4 x 400 metres Relay,0.0,7.85,17091.859905
12,Tadeusz Demboczyk,M,24.0,155.0,56.0,Poland,1980,Summer,Weightlifting,Weightlifting Men's Bantamweight,3.0,7.85,17091.859905
13,Lech asko,M,24.0,197.0,88.0,Poland,1980,Summer,Volleyball,Volleyball Men's Volleyball,0.0,7.85,17091.859905
14,Marek bik,M,22.0,180.0,80.0,Poland,1980,Summer,Canoeing,"Canoeing Men's Canadian Singles, 500 metres",0.0,7.85,17091.859905
15,Grayna Oliszewska (-Baumgarten),F,20.0,161.0,58.0,Poland,1980,Summer,Athletics,Athletics Women's 4 x 400 metres Relay,0.0,7.85,17091.859905
16,Marek bik,M,22.0,180.0,80.0,Poland,1980,Summer,Canoeing,"Canoeing Men's Canadian Singles, 1,000 metres",0.0,7.85,17091.859905
17,Grayna Oliszewska (-Baumgarten),F,20.0,161.0,58.0,Poland,1980,Summer,Athletics,Athletics Women's 400 metres,0.0,7.85,17091.859905
18,Jan Olesiski,M,23.0,186.0,72.0,Poland,1980,Summer,Modern Pentathlon,Modern Pentathlon Men's Team,0.0,7.85,17091.859905
19,Jan Olesiski,M,23.0,186.0,72.0,Poland,1980,Summer,Modern Pentathlon,Modern Pentathlon Men's Individual,0.0,7.85,17091.859905
20,Grzegorz Jzef Stellak,M,29.0,197.0,95.0,Poland,1980,Summer,Rowing,Rowing Men's Coxed Fours,3.0,7.85,17091.859905
21,Grzegorz Jzef Stellak,M,29.0,197.0,95.0,Poland,1980,Summer,Rowing,Rowing Men's Coxed Eights,0.0,7.85,17091.859905
22,Krzysztof Potaczek,M,22.0,176.0,66.0,Poland,1980,Summer,Gymnastics,Gymnastics Men's Pommelled Horse,0.0,7.85,17091.859905
23,Andrzej Mikina,M,24.0,188.0,90.0,Poland,1980,Summer,Hockey,Hockey Men's Hockey,0.0,7.85,17091.859905
24,Tomasz Busse,M,23.0,188.0,92.0,Poland,1980,Summer,Wrestling,"Wrestling Men's Heavyweight, Freestyle",0.0,7.85,17091.859905
25,Krzysztof Jzef Stefaniak,M,22.0,182.0,66.0,Poland,1980,Summer,Shooting,"Shooting Mixed Small-Bore Rifle, Prone, 50 metres",0.0,7.85,17091.859905
26,Jerzy Andrzej Potz,M,27.0,180.0,85.0,Poland,1980,Winter,Ice Hockey,Ice Hockey Men's Ice Hockey,0.0,7.85,17091.859905
27,Danuta Bukowska (-Milej),F,21.0,178.0,57.0,Poland,1980,Summer,Athletics,Athletics Women's High Jump,0.0,7.85,17091.859905
28,Bohdan Adam Buakowski,M,30.0,181.0,67.0,Poland,1980,Summer,Athletics,Athletics Men's 50 kilometres Walk,0.0,7.85,17091.859905
29,Bohdan Adam Buakowski,M,30.0,181.0,67.0,Poland,1980,Summer,Athletics,Athletics Men's 20 kilometres Walk,0.0,7.85,17091.859905
...,...,...,...,...,...,...,...,...,...,...,...,...,...
130294,Saa Mii,M,29.0,198.0,109.0,Montenegro,2016,Summer,Water Polo,Water Polo Men's Water Polo,0.0,10.55,9314.297972
130295,Sran Mrvaljevi,M,32.0,186.0,85.0,Montenegro,2016,Summer,Judo,Judo Men's Half-Middleweight,0.0,10.55,9314.297972
130296,Ema Ramusovi,F,19.0,183.0,78.0,Montenegro,2016,Summer,Handball,Handball Women's Handball,0.0,10.55,9314.297972
130297,Aleksandar Radovi,M,29.0,191.0,98.0,Montenegro,2016,Summer,Water Polo,Water Polo Men's Water Polo,0.0,10.55,9314.297972
130298,Zdravko Radi,M,37.0,193.0,96.0,Montenegro,2016,Summer,Water Polo,Water Polo Men's Water Polo,0.0,10.55,9314.297972
130299,"Jovanka ""Jova"" Radievi",F,29.0,170.0,68.0,Montenegro,2016,Summer,Handball,Handball Women's Handball,0.0,10.55,9314.297972
130300,Bojana Popovi (Petrovi-),F,36.0,188.0,86.0,Montenegro,2016,Summer,Handball,Handball Women's Handball,0.0,10.55,9314.297972
130301,Marina Vukevi-Raji,F,22.0,175.0,70.0,Montenegro,2016,Summer,Handball,Handball Women's Handball,0.0,10.55,9314.297972
130302,Danka Kovini,F,21.0,169.0,67.0,Montenegro,2016,Summer,Tennis,Tennis Women's Singles,0.0,10.55,9314.297972
130303,Drako Brguljan,M,31.0,194.0,92.0,Montenegro,2016,Summer,Water Polo,Water Polo Men's Water Polo,0.0,10.55,9314.297972
130304,Darko Brguljan,M,25.0,180.0,97.0,Montenegro,2016,Summer,Water Polo,Water Polo Men's Water Polo,0.0,10.55,9314.297972
130305,Katarina Bulatovi,F,31.0,186.0,71.0,Montenegro,2016,Summer,Handball,Handball Women's Handball,0.0,10.55,9314.297972
130306,Anela Bulatovi,F,29.0,175.0,67.0,Montenegro,2016,Summer,Handball,Handball Women's Handball,0.0,10.55,9314.297972
130307,Logona Esau,M,21.0,163.0,69.0,Tuvalu,2008,Summer,Weightlifting,Weightlifting Men's Lightweight,0.0,28.00,3949.793733
130308,Tuau Lapua Lapua,M,21.0,140.0,62.0,Tuvalu,2012,Summer,Weightlifting,Weightlifting Men's Featherweight,0.0,28.00,3949.793733
130309,Tavevele Noa,M,20.0,176.0,74.0,Tuvalu,2012,Summer,Athletics,Athletics Men's 100 metres,0.0,28.00,3949.793733
130310,Etimoni Timuani,M,24.0,184.0,72.0,Tuvalu,2016,Summer,Athletics,Athletics Men's 100 metres,0.0,28.00,3949.793733
130311,Anju Jason,M,20.0,178.0,80.0,Marshall Islands,2008,Summer,Taekwondo,Taekwondo Men's Welterweight,0.0,27.40,3965.345511
130312,Julianne Kirchner,F,16.0,138.0,54.0,Marshall Islands,2008,Summer,Swimming,Swimming Women's 50 metres Freestyle,0.0,27.40,3965.345511
130313,Haley Nicole Nemra,F,18.0,168.0,59.0,Marshall Islands,2008,Summer,Athletics,Athletics Women's 800 metres,0.0,27.40,3965.345511
130314,Jared J. Heine,M,23.0,179.0,70.0,Marshall Islands,2008,Summer,Swimming,Swimming Men's 100 metres Backstroke,0.0,27.40,3965.345511
130315,Timi Hilly Garstang,M,25.0,175.0,73.0,Marshall Islands,2012,Summer,Athletics,Athletics Men's 100 metres,0.0,27.40,3965.345511
130316,Giordan Harris,M,19.0,185.0,99.0,Marshall Islands,2012,Summer,Swimming,Swimming Men's 50 metres Freestyle,0.0,27.40,3965.345511
130317,"Ann-Marie ""Annie"" Hepler",F,16.0,167.0,68.0,Marshall Islands,2012,Summer,Swimming,Swimming Women's 50 metres Freestyle,0.0,27.40,3965.345511
130318,Haley Nicole Nemra,F,22.0,168.0,59.0,Marshall Islands,2012,Summer,Athletics,Athletics Women's 800 metres,0.0,27.40,3965.345511
130319,Colleen Furgeson,F,17.0,176.0,65.0,Marshall Islands,2016,Summer,Swimming,Swimming Women's 50 metres Freestyle,0.0,27.40,3965.345511
130320,"Mathlynn Langtor ""Mattie"" Sasser",F,19.0,158.0,58.0,Marshall Islands,2016,Summer,Weightlifting,Weightlifting Women's Lightweight,0.0,27.40,3965.345511
130321,Mariana Cress,F,17.0,159.0,52.0,Marshall Islands,2016,Summer,Athletics,Athletics Women's 100 metres,0.0,27.40,3965.345511
130322,Richson Simeon,M,18.0,155.0,78.0,Marshall Islands,2016,Summer,Athletics,Athletics Men's 100 metres,0.0,27.40,3965.345511
130323,Giordan Harris,M,23.0,185.0,99.0,Marshall Islands,2016,Summer,Swimming,Swimming Men's 50 metres Freestyle,0.0,27.40,3965.345511